### PR TITLE
Remove Depandabot from OVMS main branch

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
### 🛠 Summary

JIRA/Issue if applicable.
Describe the changes.
Depandabot is configured on OVMS `main` branch but we don't use `main` of OVMS for any activity. I had raised this PR to remove Depandabot from OVMS `main` branch because it causes to create lots of PR/branchs to bump versions.

### 🧪 Checklist

- [ ] Unit tests added.
- [ ] The documentation updated.
- [ ] Change follows security best practices.
``

### CODE REVIEW

**Comment by RH-steve-grubb** [comment]
Sounds like a good idea. LGTM.

**Comment by dtrifiro** [comment]
Why is this required?

**Comment by vaibhavjainwiz** [comment]
> Why is this required?

Dependabot is just creating branches and PR which are not used.

**Comment by dtrifiro** [comment]
Are we not doing dependabot updates in this repo?

**Comment by RH-steve-grubb** [comment]
> Are we not doing dependabot updates in this repo? Is there a jira for this?

No. The repo is updated by hand on the branch we intend to release. AFAIK, it has always been that way.

**Pull request merged**
